name: Build

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
        with:
          repository: maximzubkov/positional-bias
          token: ${{ secrets.ACCESS_TOKEN }}
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        python setup.py build_ext --inplace
        pip install -e .
        sh scripts/install_pos_bias.sh
    - name: flake8
      run: |
        flake8 --max-line-length=120 --exclude="test_*.py" .
    - name: pytest
      run: |
        pytest .